# This file is for use with the AWS ecs-cli tool
---
version: "3"
services:
  app:
    image: ${AWS_ACCOUNT}.dkr.ecr.eu-west-1.amazonaws.com/faith-app:latest
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: ${ECS_MY_REPO_NAME}
        awslogs-region: eu-west-1
        awslogs-stream-prefix: app
